### ISSUE TITLE
AR Drone 2 With ApprilTag

### ISSUE THREAD

**Issue by thaithanh1303** [lukaslaobeyer/AutoFlight_v1#1]
Hello 
I have a project that control the drone by Apriltag.
However when i try to use the autoflight and test the AprilTag. I have a problem that get information of the  imgproc.tag_detections(). It is a list of tupes which contains ( detection id , detection.goods , points)
Now i want to take the id from the list but dont know how.
In the picture i want to take information of tup1.

Would you help me please ?

Sorry i am a beginner in this field. Please help me.
![ttt](https://cloud.githubusercontent.com/assets/15164673/13862454/13a09f28-ec9c-11e5-81f7-c4109dd34393.png)

**Comment by lukaslaobeyer** [comment]
Hi!

Sorry for the delay in the response.

As `tag_detections()` returns a list of tuples (as you said), I'd suggest just iterating over the results like this:

``` python
detections = imgproc.tag_detections()
for (id, good, points) in detections:
    # Use the id and points variables to get information about the tag
    # For example:
    print(id)
```

Also, if you want to continously get new results you should create a loop and call `tag_detections()` repeatedly.

For example:

``` python
imgproc.start_tag_detector()

while True:
    detections = imgproc.tag_detections()
    for (id, good, points) in detections:
        # Use the id and points variables to get information about the tag
        # For example:
        print(id)
    time.sleep(0.025)
```

I haven't tested this code so there could be typos, but it should work.

**Comment by lukaslaobeyer** [comment]
For a tested, fully working example see https://github.com/lukaslaobeyer/AutoFlight_v1/blob/master/autoscript/examples/vision/apriltags.ascr

You might need to set the tag family first, using `imgproc.set_tag_family(family)`
